// Generated by CoffeeScript 1.6.3
'use strict';
var FeedsView;

FeedsView = (function() {
  FeedsView.liTemplate = Handlebars.compile($('#feed-li-tpl').html());

  FeedsView.template = Handlebars.compile($('#feeds-tpl').html());

  function FeedsView(store) {
    var _this = this;
    this.findByName = function() {
      var _this = this;
      return store.findByName($('.search-key').val(), function(results) {
        var $el;
        return $el = $('.feed-list', '.homePage').html(FeedsView.liTemplate(results));
      });
    };
    this.render = function() {
      _this.el.html(FeedsView.template());
      return _this;
    };
    this.el = $('<article class="page homePage" />').on('keyup', '.search-key', this.findByName);
    $.doTimeout(100, function() {
      $('.search-key', _this.el).focus();
      return _this.findByName();
    });
  }

  return FeedsView;

})();
